//
// Created by szymon on 28.08.22.
//

#ifndef CODEJAM_GLOBALS_HPP
#define CODEJAM_GLOBALS_HPP

#define SCREENWIDTH 1280
#define SCREENHEIGHT 720
#define TILEWIDTH 16
#define TILEHEIGHT 16

#endif //CODEJAM_GLOBALS_HPP
